#!/bin/bash

function create_ldconf() {
cat > /etc/ld.so.conf.d/0-rockchip.conf <<EOF
# DO NOT EDIT!
# This is autogenerated by /usr/local/bin/rockchip.sh

/usr/lib/${1}
EOF
}

if [ ! -e "/etc/ld.so.conf.d/0-rockchip.conf" ]
then
    echo "It's the first time booting."
    echo "The rootfs will be configured, according to your chip."

    COMPATIBLE=$(cat /proc/device-tree/compatible)
    CHIPNAME=${COMPATIBLE##*rockchip,}

    create_ldconf ${CHIPNAME}
    ldconfig
fi


